# nine.ch App Deployment Configuration
# Minimal static site deployment

name: ikignosis-org
app_type: static

build:
  base_image: nginx:alpine
  build_steps:
    - cp -r * /usr/share/nginx/html/

runtime:
  ports:
    - 80
  health_check:
    path: /index.html
    interval: 30s
    timeout: 5s

deployment:
  branch: main